2025-03-31 14:07:18,001 INFO    Thread-3  :41436 [wandb_setup.py:_flush():67] Current SDK version is 0.19.8
2025-03-31 14:07:18,001 INFO    Thread-3  :41436 [wandb_setup.py:_flush():67] Configure stats pid to 41436
2025-03-31 14:07:18,002 INFO    Thread-3  :41436 [wandb_setup.py:_flush():67] Loading settings from /Users/gichanpark/.config/wandb/settings
2025-03-31 14:07:18,002 INFO    Thread-3  :41436 [wandb_setup.py:_flush():67] Loading settings from /Users/gichanpark/Desktop/castone_design/wandb/settings
2025-03-31 14:07:18,002 INFO    Thread-3  :41436 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-31 14:07:18,002 INFO    Thread-3  :41436 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /Users/gichanpark/Desktop/castone_design/wandb/run-20250331_140717-b5tmta2a/logs/debug.log
2025-03-31 14:07:18,002 INFO    Thread-3  :41436 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /Users/gichanpark/Desktop/castone_design/wandb/run-20250331_140717-b5tmta2a/logs/debug-internal.log
2025-03-31 14:07:18,002 INFO    Thread-3  :41436 [wandb_init.py:init():761] calling init triggers
2025-03-31 14:07:18,003 INFO    Thread-3  :41436 [wandb_init.py:init():766] wandb.init called with sweep_config: {'batch_size': 8, 'data_path': './finger_printing/datasets/augmented/wifi_rssi_log_augmented_20250331_000650.csv', 'dropout_rate': 0.3, 'early_stopping': False, 'embedding_dim': 8, 'epochs': 100, 'learning_rate': 0.001, 'scheduler': True, 'transformer_heads': 4, 'transformer_layers': 2}
config: {'_wandb': {}}
2025-03-31 14:07:18,003 INFO    Thread-3  :41436 [wandb_init.py:init():784] starting backend
2025-03-31 14:07:18,003 INFO    Thread-3  :41436 [wandb_init.py:init():788] sending inform_init request
2025-03-31 14:07:18,032 INFO    Thread-3  :41436 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2025-03-31 14:07:18,032 INFO    Thread-3  :41436 [wandb_init.py:init():798] backend started and connected
2025-03-31 14:07:18,033 INFO    Thread-3  :41436 [wandb_run.py:_config_callback():1261] config_cb None None {'batch_size': 8, 'data_path': './finger_printing/datasets/augmented/wifi_rssi_log_augmented_20250331_000650.csv', 'dropout_rate': 0.3, 'early_stopping': False, 'embedding_dim': 8, 'epochs': 100, 'learning_rate': 0.001, 'scheduler': True, 'transformer_heads': 4, 'transformer_layers': 2}
2025-03-31 14:07:18,036 INFO    Thread-3  :41436 [wandb_init.py:init():891] updated telemetry
2025-03-31 14:07:18,056 INFO    Thread-3  :41436 [wandb_init.py:init():915] communicating run to backend with 90.0 second timeout
2025-03-31 14:07:18,502 INFO    Thread-3  :41436 [wandb_init.py:init():990] starting run threads in backend
2025-03-31 14:07:18,566 INFO    Thread-3  :41436 [wandb_run.py:_console_start():2375] atexit reg
2025-03-31 14:07:18,567 INFO    Thread-3  :41436 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-31 14:07:18,567 INFO    Thread-3  :41436 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-31 14:07:18,567 INFO    Thread-3  :41436 [wandb_run.py:_redirect():2315] Redirects installed.
2025-03-31 14:07:18,568 INFO    Thread-3  :41436 [wandb_init.py:init():1032] run started, returning control to user process
2025-03-31 14:07:18,569 INFO    Thread-3  :41436 [wandb_run.py:_config_callback():1261] config_cb None None {}
2025-03-31 14:09:48,125 INFO    Thread-3  :41436 [wandb_run.py:_finish():2112] finishing run dguyanglab/wifi-fingerprinting/b5tmta2a
2025-03-31 14:09:48,125 INFO    Thread-3  :41436 [wandb_run.py:_atexit_cleanup():2340] got exitcode: 1
2025-03-31 14:09:48,125 INFO    Thread-3  :41436 [wandb_run.py:_restore():2322] restore
2025-03-31 14:09:48,125 INFO    Thread-3  :41436 [wandb_run.py:_restore():2328] restore done
2025-03-31 14:09:48,625 INFO    MsgRouterThr:41436 [mailbox.py:close():129] Closing mailbox, abandoning 2 handles.
2025-03-31 14:09:48,627 INFO    Thread-3  :41436 [wandb_run.py:_restore():2322] restore
2025-03-31 14:09:48,627 INFO    Thread-3  :41436 [wandb_run.py:_restore():2328] restore done
2025-03-31 14:09:48,630 ERROR   Thread-3  :41436 [wandb_run.py:_atexit_cleanup():2361] Problem finishing run
Traceback (most recent call last):
  File "/Users/gichanpark/Desktop/castone_design/finger_printing/train_CNNTransformer_sweep.py", line 181, in train_model
    loss = criterion(outputs, labels_batch)
  File "/opt/homebrew/anaconda3/envs/capstone/lib/python3.8/site-packages/torch/_tensor.py", line 492, in backward
    torch.autograd.backward(
  File "/opt/homebrew/anaconda3/envs/capstone/lib/python3.8/site-packages/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
Exception

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/envs/capstone/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 2352, in _atexit_cleanup
    self._on_finish()
  File "/opt/homebrew/anaconda3/envs/capstone/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 2609, in _on_finish
    wait_with_progress(
  File "/opt/homebrew/anaconda3/envs/capstone/lib/python3.8/site-packages/wandb/sdk/mailbox/wait_with_progress.py", line 24, in wait_with_progress
    return wait_all_with_progress(
  File "/opt/homebrew/anaconda3/envs/capstone/lib/python3.8/site-packages/wandb/sdk/mailbox/wait_with_progress.py", line 70, in wait_all_with_progress
    return _wait_handles(handle_list, timeout=progress_after)
  File "/opt/homebrew/anaconda3/envs/capstone/lib/python3.8/site-packages/wandb/sdk/mailbox/wait_with_progress.py", line 110, in _wait_handles
    results.append(handle.wait_or(timeout=remaining_timeout))
  File "/opt/homebrew/anaconda3/envs/capstone/lib/python3.8/site-packages/wandb/sdk/mailbox/mailbox_handle.py", line 122, in wait_or
    return self._fn(self._handle.wait_or(timeout=timeout))
  File "/opt/homebrew/anaconda3/envs/capstone/lib/python3.8/site-packages/wandb/sdk/mailbox/response_handle.py", line 98, in wait_or
    raise HandleAbandonedError()
wandb.sdk.mailbox.mailbox_handle.HandleAbandonedError
