2025-03-31 14:46:32,897 INFO    Thread-3  :67564 [wandb_setup.py:_flush():67] Current SDK version is 0.19.8
2025-03-31 14:46:32,898 INFO    Thread-3  :67564 [wandb_setup.py:_flush():67] Configure stats pid to 67564
2025-03-31 14:46:32,898 INFO    Thread-3  :67564 [wandb_setup.py:_flush():67] Loading settings from /Users/gichanpark/.config/wandb/settings
2025-03-31 14:46:32,898 INFO    Thread-3  :67564 [wandb_setup.py:_flush():67] Loading settings from /Users/gichanpark/Desktop/castone_design/wandb/settings
2025-03-31 14:46:32,898 INFO    Thread-3  :67564 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-31 14:46:32,898 INFO    Thread-3  :67564 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /Users/gichanpark/Desktop/castone_design/wandb/run-20250331_144632-ui2rkang/logs/debug.log
2025-03-31 14:46:32,898 INFO    Thread-3  :67564 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /Users/gichanpark/Desktop/castone_design/wandb/run-20250331_144632-ui2rkang/logs/debug-internal.log
2025-03-31 14:46:32,899 INFO    Thread-3  :67564 [wandb_init.py:init():761] calling init triggers
2025-03-31 14:46:32,899 INFO    Thread-3  :67564 [wandb_init.py:init():766] wandb.init called with sweep_config: {'batch_size': 4, 'data_path': './finger_printing/datasets/augmented/wifi_rssi_log_augmented_20250331_000650.csv', 'dropout_rate': 0.5, 'early_stopping': True, 'embedding_dim': 32, 'epochs': 100, 'learning_rate': 0.001, 'scheduler': False, 'transformer_heads': 8, 'transformer_layers': 2}
config: {'_wandb': {}}
2025-03-31 14:46:32,899 INFO    Thread-3  :67564 [wandb_init.py:init():784] starting backend
2025-03-31 14:46:32,899 INFO    Thread-3  :67564 [wandb_init.py:init():788] sending inform_init request
2025-03-31 14:46:32,943 INFO    Thread-3  :67564 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2025-03-31 14:46:32,943 INFO    Thread-3  :67564 [wandb_init.py:init():798] backend started and connected
2025-03-31 14:46:32,944 INFO    Thread-3  :67564 [wandb_run.py:_config_callback():1261] config_cb None None {'batch_size': 4, 'data_path': './finger_printing/datasets/augmented/wifi_rssi_log_augmented_20250331_000650.csv', 'dropout_rate': 0.5, 'early_stopping': True, 'embedding_dim': 32, 'epochs': 100, 'learning_rate': 0.001, 'scheduler': False, 'transformer_heads': 8, 'transformer_layers': 2}
2025-03-31 14:46:32,947 INFO    Thread-3  :67564 [wandb_init.py:init():891] updated telemetry
2025-03-31 14:46:32,965 INFO    Thread-3  :67564 [wandb_init.py:init():915] communicating run to backend with 90.0 second timeout
2025-03-31 14:46:33,333 ERROR   Thread-3  :67564 [wandb_init.py:init():1478] error in wandb.init()
Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/envs/capstone/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1468, in init
    return wi.init(run_settings, run_config)
  File "/opt/homebrew/anaconda3/envs/capstone/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 941, in init
    result = wait_with_progress(
  File "/opt/homebrew/anaconda3/envs/capstone/lib/python3.8/site-packages/wandb/sdk/mailbox/wait_with_progress.py", line 24, in wait_with_progress
    return wait_all_with_progress(
  File "/opt/homebrew/anaconda3/envs/capstone/lib/python3.8/site-packages/wandb/sdk/mailbox/wait_with_progress.py", line 70, in wait_all_with_progress
    return _wait_handles(handle_list, timeout=progress_after)
  File "/opt/homebrew/anaconda3/envs/capstone/lib/python3.8/site-packages/wandb/sdk/mailbox/wait_with_progress.py", line 110, in _wait_handles
    results.append(handle.wait_or(timeout=remaining_timeout))
  File "/opt/homebrew/anaconda3/envs/capstone/lib/python3.8/site-packages/wandb/sdk/mailbox/mailbox_handle.py", line 122, in wait_or
    return self._fn(self._handle.wait_or(timeout=timeout))
  File "/opt/homebrew/anaconda3/envs/capstone/lib/python3.8/site-packages/wandb/sdk/mailbox/response_handle.py", line 88, in wait_or
    if not self._event.wait(timeout=timeout):
  File "/opt/homebrew/anaconda3/envs/capstone/lib/python3.8/threading.py", line 558, in wait
    signaled = self._cond.wait(timeout)
  File "/opt/homebrew/anaconda3/envs/capstone/lib/python3.8/threading.py", line 306, in wait
    gotit = waiter.acquire(True, timeout)
Exception
